allowBuilds:
  better-sqlite3: true
  esbuild: true
  lefthook: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.37 || 4.0.43 || 4.0.44'
  - ai@7.0.48 || 7.0.55 || 7.0.56
  - tsx@4.23.4 || 4.23.9 || 4.23.10
  - '@ai-sdk/anthropic@4.0.33 || 4.0.34'
  - '@ai-sdk/openai@4.0.33 || 4.0.34'
  - '@ai-sdk/provider-utils@5.0.23'
  - '@ai-sdk/provider@4.0.6'
onlyBuiltDependencies:
  - esbuild
  - lefthook
